apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-vaults-pv-claim
spec:
#  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.data_volume.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-config-pv-claim
spec:
#  storageClassName: {{ .Values.config_volume.size }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.config_volume.size }}
