apiVersion: v1
kind: Service
metadata:
  name: {{ include "obsidian.fullname" . }}
  labels:
    {{- include "obsidian.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.obsidian.port }}
      targetPort: http
      protocol: TCP
      name: vnc
    - port: {{ .Values.service.dev_proxy.port }}
      targetPort: http
      protocol: TCP
      name: devport
  selector:
    {{- include "obsidian.selectorLabels" . | nindent 4 }}
