apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "obsidian.fullname" . }}
  labels:
    {{- include "obsidian.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "obsidian.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "obsidian.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "obsidian.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.obsidian.repository }}:{{ .Values.image.obsidian.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.obsidian.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.obsidian.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.obsidian.port }}
            initialDelaySeconds: 60
            periodSeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: vaults
              mountPath: "/vaults"
              readOnly: false
            - name: config
              mountPath: "/config"
              readOnly: false
        - name: {{ .Release.Name }}-devport-proxy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.proxy.repository }}:{{ .Values.image.proxy.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.proxy.pullPolicy }}
          args: ["TCP-LISTEN:{{ .Values.service.dev_proxy.port }},fork", "TCP:localhost:8315"]
          ports:
            - name: http
              containerPort: {{ .Values.service.dev_proxy.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.dev_proxy.port }}
            initialDelaySeconds: 60
            periodSeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        -
          name: vaults
          persistentVolumeClaim:
           claimName: {{ .Release.Name }}-vaults-pv-claim
        -
          name: config
          persistentVolumeClaim:
           claimName: {{ .Release.Name }}-config-pv-claim
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
